// Code generated by ngcheckers test. DO NOT EDIT.

// This file carries the conventional generated-code marker before its package
// clause, so ast.IsGenerated reports it as generated and the analyzer must
// skip it. The os.IsNotExist below would otherwise be reported; the absence of
// any expectation comment asserts that it is not.
package a

import "os"

// Generated calls a forbidden predicate in a generated file; it must not be
// reported.
func Generated(err error) bool {
	return os.IsNotExist(err)
}
