// Code generated by ngcheckers test. DO NOT EDIT.

// This file carries the conventional generated-code marker before its package
// clause, so ast.IsGenerated reports it as generated and the analyzer must skip
// it. The "omitempty" below would otherwise be reported; the absence of any
// expectation comment asserts that it is not.
package a

// Generated has an omitempty that must not be reported because the file is
// generated.
type Generated struct {
	Name string `json:"name,omitempty"`
}
